version: "3.8"
volumes:
  dbvolume:


services:
    db: 
        image: mysql:latest
        container_name: db
        restart: always
        volumes:
            - dbvolume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        expose:
          - 3306
    app: 
        build: .
        container_name: app
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
            - elasticsearch
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            DB_PORT: 3306
    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        volumes:
            - ./tmp/redis_data:/var/lib/redis/data
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
        container_name: elasticsearch
        volumes:
            - dbvolume:/var/lib/elasticsearch
        expose:
            - 9200
        environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node']
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
            - ".:/app"
        environment:
            RAILS_ENV: development
            REDIS_HOST: redis
            REDIS_PORT: 6379
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            DB_PORT: 3306
        depends_on:
            - "redis"
